name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # 每12小时运行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake - Dark
        uses: Platane/snk@master
        id: snake-dark
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
          snake_color: "#39D353"
          bg_color: "#0d1117"

      - name: Generate Snake - Light
        uses: Platane/snk@master
        id: snake-light
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          outputs: |
            dist/github-contribution-grid-snake.svg
          snake_color: "#39D353"
          bg_color: "#ffffff"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
